### PR TITLE
fix: fix broken release action

### PR DESCRIPTION
**Pull request by bohan-amplitude**
### Summary

fix release github aciton

### Checklist

* [x] Does your PR title have the correct [title format](https://github.com/amplitude/Amplitude-Python/blob/main/CONTRIBUTING.md#pr-commit-title-conventions)?
* Does your PR have a breaking change?:  no

### CODE REVIEW

**Comment by kevinpagtakhan** [comment]
How is status quo broken and how are the changes fixing the issue?

**Comment by bohan-amplitude** [comment]
> How is status quo broken and how are the changes fixing the issue?

The dry-run using semantic-release command success but the relekang/python-semantic-release@master action failed with some debug info seems like can not get new version number. It works fine before. I changed to use semantic-release command and tested successfully.

**Comment by kevinpagtakhan** [comment]
Have we considered pinning to a version instead of master so we get consistent behavior?

**Comment by bohan-amplitude** [comment]
> Have we considered pinning to a version instead of master so we get consistent behavior?
> 
> EDIT: I mean pinning the version for `relekang/python-semantic-release`

I don't know what version they have, the only branch of the repo is master and the doc gives example to use @master. 
This action is a wrapper of semantic-release command from python-semantic-release package. It also has other problems like can't set commit user and email and use actions-bot by default. Command is more configurable and read config file pyproject.toml from the project repo, could be a better choice.

**Comment by kevinpagtakhan** [comment]
Gotcha, if we generally prefer the new approach then this should be fine.

**Review by kevinpagtakhan — APPROVED** [review]

**Pull request merged**
