### PR TITLE
fix: set correct fetch-depth for semantic release

### PR DESCRIPTION
**Pull request by bohan-amplitude**
### Summary

set fetch-depth to 0 for checkout action

### Checklist

* [x] Does your PR title have the correct [title format](https://github.com/amplitude/Amplitude-Python/blob/main/CONTRIBUTING.md#pr-commit-title-conventions)?
* Does your PR have a breaking change?:  no

### CODE REVIEW

**Review by kevinpagtakhan — APPROVED** [review]
is this to fetch the tags to determine the new correct version to bump to?

**Review by qingzhuozhen — APPROVED** [review]
This is for checkout action. Set fetch-depth: 0 means to fetch all history for all branches and tags

**Comment by kevinpagtakhan** [comment]
> This is for checkout action. Set fetch-depth: 0 means to fetch all history for all branches and tags

what are we trying to achieve by fetching all branches and tags? just wanted to make sure the PR has enough context on what the issue it's trying to solve

**Comment by bohan-amplitude** [comment]
> is this to fetch the tags to determine the new correct version to bump to?

Yes, semantic release need whole commit history to get new version. Otherwise it can only see the last commit.

**Pull request merged**
