### PR TITLE
test:Enable testing with multiple versions of python

### PR DESCRIPTION
**Pull request by ssbarnea**
### Checklist

* [x] Does your PR title have the correct [title format](https://github.com/amplitude/Amplitude-Python/blob/main/CONTRIBUTING.md#pr-commit-title-conventions)?
* Does your PR have a breaking change?:

### CODE REVIEW

**Comment by qingzhuozhen** [comment]
Hi @ssbarnea Thanks for contributing to our Python SDK! It seems python 3.6 is not included in ubuntu 22 referring to https://github.com/actions/setup-python/issues/544. Would you mind removing the 3.6 from this PR? Or maybe run on a different ubuntu version?

**Comment by ssbarnea** [comment]
@qingzhuozhen this should work, if no you better push the required changes on top of it as not being able to test it myself is demoralizing.

**Comment by qingzhuozhen** [comment]
Seems there is an error in the yml file, https://github.com/amplitude/Amplitude-Python/actions/runs/3882662317

**Comment by qingzhuozhen** [comment]
Hi @ssbarnea I just merged https://github.com/amplitude/Amplitude-Python/pull/42 with similar changes in this pull request. Closing this for now and feel free to let me know if there is any other concern.

**Pull request closed without merging**
